// AgroVista Authentic Realistic Seed Data
// Focus: Telangana Agricultural Ecosystem & Direct Farmer Commerce

import {
  Product,
  MarketPrice,
  GovernmentScheme,
  WeatherData,
  DigitalLiteracyGuide,
  FertilizerGuidance,
  AIPrediction,
} from '@/types';

export const SEED_FARMERS = [
  {
    id: "f1",
    user_id: "u_farmer_1",
    name: "Ramulu Goud",
    phone: "9848022334",
    email: "ramulu.farmer@agrovista.in",
    role: "FARMER" as const,
    language: "te" as const,
    farm_name: "Goud Natural Organics",
    village: "Parvathagiri",
    district: "Warangal",
    state: "Telangana",
    pincode: "506365",
    farm_size: "5.5 Acres",
    crops: ["Chili", "Paddy", "Turmeric"],
    verification_status: "VERIFIED" as const,
  },
  {
    id: "f2",
    user_id: "u_farmer_2",
    name: "Lakshmi Bai",
    phone: "9440188992",
    email: "lakshmi.shamshabad@agrovista.in",
    role: "FARMER" as const,
    language: "te" as const,
    farm_name: "Green Valley Agro Farm",
    village: "Shamshabad",
    district: "Rangareddy",
    state: "Telangana",
    pincode: "501218",
    farm_size: "3.2 Acres",
    crops: ["Tomato", "Spinach", "Okra", "Brinjal"],
    verification_status: "VERIFIED" as const,
  },
  {
    id: "f3",
    user_id: "u_farmer_3",
    name: "Mallesh Yadav",
    phone: "9989011223",
    email: "mallesh.orchards@agrovista.in",
    role: "FARMER" as const,
    language: "en" as const,
    farm_name: "Deccan Gold Orchards",
    village: "Gajwel",
    district: "Siddipet",
    state: "Telangana",
    pincode: "502278",
    farm_size: "8.0 Acres",
    crops: ["Banganapalli Mango", "Guava", "Papaya"],
    verification_status: "VERIFIED" as const,
  },
];

export const SEED_CUSTOMERS = [
  {
    id: "c1",
    user_id: "u_customer_1",
    name: "Priya Sharma",
    phone: "9876543210",
    email: "priya.sharma@example.com",
    role: "CUSTOMER" as const,
    address: "Flat 402, Sunshine Heights, Madhapur",
    city: "Hyderabad",
    state: "Telangana",
    pincode: "500081",
  },
  {
    id: "c2",
    user_id: "u_customer_2",
    name: "Rajesh Reddy",
    phone: "9123456780",
    email: "rajesh.reddy@example.com",
    role: "CUSTOMER" as const,
    address: "H.No 12-4-89, Marredpally",
    city: "Secunderabad",
    state: "Telangana",
    pincode: "500026",
  },
];

export const SEED_PRODUCTS: Product[] = [
  {
    id: "p1",
    farmer_id: "f2",
    crop_name: "Farm Fresh Country Tomatoes (నాటు టమాటాలు)",
    category: "VEGETABLES",
    description: "Naturally ripened, vine-fresh country tomatoes harvested at 5:00 AM from our Shamshabad farm. Rich in lycopene and naturally tangy flavor. Zero chemical sprays during harvesting week.",
    image_url: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=800&auto=format&fit=crop&q=80",
    quantity_available: 120,
    unit: "kg",
    farmer_price: 32,
    market_reference_price: 38,
    status: "AVAILABLE",
    harvest_date: "2026-09-29",
    is_organic: true,
    created_at: "2026-09-29T06:00:00Z",
    updated_at: "2026-09-29T06:00:00Z",
    farmer: {
      id: "f2",
      user_id: "u_farmer_2",
      farm_name: "Green Valley Agro Farm",
      village: "Shamshabad",
      district: "Rangareddy",
      state: "Telangana",
      pincode: "501218",
      farm_size: "3.2 Acres",
      crops: ["Tomato", "Spinach"],
      verification_status: "VERIFIED",
      user: {
        id: "u_farmer_2",
        name: "Lakshmi Bai",
        phone: "9440188992",
        role: "FARMER",
        language: "te",
        is_verified: true,
        created_at: "2026-01-01",
        updated_at: "2026-01-01",
      },
    },
  },
  {
    id: "p2",
    farmer_id: "f1",
    crop_name: "Warangal Teja Dry Red Chili (వరంగల్ తేజా మిర్చి)",
    category: "SPICES",
    description: "World-famous GI-tagged Warangal Teja Red Chili. Sun-dried on hygienic mats, vibrant deep red color with exceptional high pungency (SHU 75,000+). Direct from Enumamula agricultural belt.",
    image_url: "https://images.unsplash.com/photo-1588252303782-cb80119abd6d?w=800&auto=format&fit=crop&q=80",
    quantity_available: 350,
    unit: "kg",
    farmer_price: 210,
    market_reference_price: 235,
    status: "AVAILABLE",
    harvest_date: "2026-09-25",
    is_organic: false,
    created_at: "2026-09-26T08:30:00Z",
    updated_at: "2026-09-26T08:30:00Z",
    farmer: {
      id: "f1",
      user_id: "u_farmer_1",
      farm_name: "Goud Natural Organics",
      village: "Parvathagiri",
      district: "Warangal",
      state: "Telangana",
      pincode: "506365",
      farm_size: "5.5 Acres",
      crops: ["Chili", "Paddy"],
      verification_status: "VERIFIED",
      user: {
        id: "u_farmer_1",
        name: "Ramulu Goud",
        phone: "9848022334",
        role: "FARMER",
        language: "te",
        is_verified: true,
        created_at: "2026-01-01",
        updated_at: "2026-01-01",
      },
    },
  },
  {
    id: "p3",
    farmer_id: "f2",
    crop_name: "Hydro-Washed Tender Spinach / Palak (తాజా పాలకూర)",
    category: "VEGETABLES",
    description: "Crisp, iron-rich fresh spinach bundles. Harvested pre-dawn, washed in clean mineral water and bundled with eco-friendly twine. Perfect for Telangana palak pappu.",
    image_url: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=800&auto=format&fit=crop&q=80",
    quantity_available: 80,
    unit: "kg",
    farmer_price: 25,
    market_reference_price: 32,
    status: "AVAILABLE",
    harvest_date: "2026-09-30",
    is_organic: true,
    created_at: "2026-09-30T05:00:00Z",
    updated_at: "2026-09-30T05:00:00Z",
    farmer: {
      id: "f2",
      user_id: "u_farmer_2",
      farm_name: "Green Valley Agro Farm",
      village: "Shamshabad",
      district: "Rangareddy",
      state: "Telangana",
      pincode: "501218",
      farm_size: "3.2 Acres",
      crops: ["Tomato", "Spinach"],
      verification_status: "VERIFIED",
      user: {
        id: "u_farmer_2",
        name: "Lakshmi Bai",
        phone: "9440188992",
        role: "FARMER",
        language: "te",
        is_verified: true,
        created_at: "2026-01-01",
        updated_at: "2026-01-01",
      },
    },
  },
  {
    id: "p4",
    farmer_id: "f3",
    crop_name: "Siddipet Sweet Banganapalli Mangoes (బేనిషా మామిడి)",
    category: "FRUITS",
    description: "Naturally tree-ripened Deccan plateau Banganapalli mangoes. Free from carbide ripening agents. Sweet, fiberless pulp with rich golden skin.",
    image_url: "https://images.unsplash.com/photo-1553279768-865429fa0078?w=800&auto=format&fit=crop&q=80",
    quantity_available: 200,
    unit: "kg",
    farmer_price: 110,
    market_reference_price: 135,
    status: "AVAILABLE",
    harvest_date: "2026-09-28",
    is_organic: true,
    created_at: "2026-09-28T09:00:00Z",
    updated_at: "2026-09-28T09:00:00Z",
    farmer: {
      id: "f3",
      user_id: "u_farmer_3",
      farm_name: "Deccan Gold Orchards",
      village: "Gajwel",
      district: "Siddipet",
      state: "Telangana",
      pincode: "502278",
      farm_size: "8.0 Acres",
      crops: ["Banganapalli Mango", "Guava"],
      verification_status: "VERIFIED",
      user: {
        id: "u_farmer_3",
        name: "Mallesh Yadav",
        phone: "9989011223",
        role: "FARMER",
        language: "en",
        is_verified: true,
        created_at: "2026-01-01",
        updated_at: "2026-01-01",
      },
    },
  },
  {
    id: "p5",
    farmer_id: "f1",
    crop_name: "Telangana Sona Low-GI Aged Rice (తెలంగాణ సోనా బియ్యం)",
    category: "GRAINS",
    description: "RNR 15048 Telangana Sona raw rice developed by PJTSAU. Clinically proven Low Glycemic Index (GI 51.5), perfect for healthy diets and diabetic families. Aged 12 months.",
    image_url: "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800&auto=format&fit=crop&q=80",
    quantity_available: 500,
    unit: "bag", // 25kg bag
    farmer_price: 1450,
    market_reference_price: 1650,
    status: "AVAILABLE",
    harvest_date: "2026-09-15",
    is_organic: false,
    created_at: "2026-09-20T10:00:00Z",
    updated_at: "2026-09-20T10:00:00Z",
    farmer: {
      id: "f1",
      user_id: "u_farmer_1",
      farm_name: "Goud Natural Organics",
      village: "Parvathagiri",
      district: "Warangal",
      state: "Telangana",
      pincode: "506365",
      farm_size: "5.5 Acres",
      crops: ["Chili", "Paddy"],
      verification_status: "VERIFIED",
      user: {
        id: "u_farmer_1",
        name: "Ramulu Goud",
        phone: "9848022334",
        role: "FARMER",
        language: "te",
        is_verified: true,
        created_at: "2026-01-01",
        updated_at: "2026-01-01",
      },
    },
  },
  {
    id: "p6",
    farmer_id: "f2",
    crop_name: "Fresh Tender Green Okra / Ladyfinger (బెండకాయలు)",
    category: "VEGETABLES",
    description: "Crisp, tender, easy-to-snap small green okra picked fresh this morning. Grown with compost and neem oil spray.",
    image_url: "https://images.unsplash.com/photo-1425543103986-22abb7d7e8d2?w=800&auto=format&fit=crop&q=80",
    quantity_available: 65,
    unit: "kg",
    farmer_price: 36,
    market_reference_price: 45,
    status: "AVAILABLE",
    harvest_date: "2026-09-30",
    is_organic: true,
    created_at: "2026-09-30T06:00:00Z",
    updated_at: "2026-09-30T06:00:00Z",
    farmer: {
      id: "f2",
      user_id: "u_farmer_2",
      farm_name: "Green Valley Agro Farm",
      village: "Shamshabad",
      district: "Rangareddy",
      state: "Telangana",
      pincode: "501218",
      farm_size: "3.2 Acres",
      crops: ["Tomato", "Okra"],
      verification_status: "VERIFIED",
      user: {
        id: "u_farmer_2",
        name: "Lakshmi Bai",
        phone: "9440188992",
        role: "FARMER",
        language: "te",
        is_verified: true,
        created_at: "2026-01-01",
        updated_at: "2026-01-01",
      },
    },
  },
];

export const SEED_MARKET_PRICES: MarketPrice[] = [
  {
    id: "mp1",
    crop_name: "Tomato",
    state: "Telangana",
    district: "Hyderabad",
    market: "Bowenpally (బోయిన్‌పల్లి)",
    min_price: 2400,
    max_price: 3600,
    modal_price: 3100,
    unit: "Quintal",
    source: "Agmarknet / Dept of Agricultural Marketing, Govt of Telangana",
    source_url: "https://agmarknet.gov.in",
    recorded_at: "2026-09-30T06:00:00Z",
  },
  {
    id: "mp2",
    crop_name: "Red Chili (Dry)",
    state: "Telangana",
    district: "Warangal",
    market: "Enumamula (ఎనుమాముల మార్కెట్ యార్డ్)",
    min_price: 18500,
    max_price: 23200,
    modal_price: 21500,
    unit: "Quintal",
    source: "Agmarknet / Dept of Agricultural Marketing, Govt of Telangana",
    source_url: "https://agmarknet.gov.in",
    recorded_at: "2026-09-30T06:00:00Z",
  },
  {
    id: "mp3",
    crop_name: "Paddy (Common / Sona)",
    state: "Telangana",
    district: "Nalgonda",
    market: "Suryapet (సూర్యాపేట)",
    min_price: 2200,
    max_price: 2450,
    modal_price: 2360,
    unit: "Quintal",
    source: "Agmarknet / Dept of Agricultural Marketing, Govt of Telangana",
    source_url: "https://agmarknet.gov.in",
    recorded_at: "2026-09-30T06:00:00Z",
  },
  {
    id: "mp4",
    crop_name: "Cotton (Kapas)",
    state: "Telangana",
    district: "Adilabad",
    market: "Adilabad Mandi (ఆదిలాబాద్ మార్కెట్)",
    min_price: 6800,
    max_price: 7650,
    modal_price: 7280,
    unit: "Quintal",
    source: "Agmarknet / Dept of Agricultural Marketing, Govt of Telangana",
    source_url: "https://agmarknet.gov.in",
    recorded_at: "2026-09-30T06:00:00Z",
  },
  {
    id: "mp5",
    crop_name: "Turmeric (Raw Finger)",
    state: "Telangana",
    district: "Nizamabad",
    market: "Nizamabad Mandi (నిజామాబాద్ పసుపు మార్కెట్)",
    min_price: 11200,
    max_price: 14800,
    modal_price: 13500,
    unit: "Quintal",
    source: "Agmarknet / Dept of Agricultural Marketing, Govt of Telangana",
    source_url: "https://agmarknet.gov.in",
    recorded_at: "2026-09-30T06:00:00Z",
  },
  {
    id: "mp6",
    crop_name: "Onion",
    state: "Telangana",
    district: "Mahabubnagar",
    market: "Mahabubnagar Yard (మహబూబ్‌నగర్)",
    min_price: 1900,
    max_price: 2800,
    modal_price: 2450,
    unit: "Quintal",
    source: "Agmarknet / Dept of Agricultural Marketing, Govt of Telangana",
    source_url: "https://agmarknet.gov.in",
    recorded_at: "2026-09-30T06:00:00Z",
  },
];

export const SEED_PRICE_HISTORY = [
  { crop_name: "Tomato", market: "Bowenpally", date: "24 Sep", modal_price: 28 },
  { crop_name: "Tomato", market: "Bowenpally", date: "25 Sep", modal_price: 29 },
  { crop_name: "Tomato", market: "Bowenpally", date: "26 Sep", modal_price: 30 },
  { crop_name: "Tomato", market: "Bowenpally", date: "27 Sep", modal_price: 32 },
  { crop_name: "Tomato", market: "Bowenpally", date: "28 Sep", modal_price: 31 },
  { crop_name: "Tomato", market: "Bowenpally", date: "29 Sep", modal_price: 33 },
  { crop_name: "Tomato", market: "Bowenpally", date: "30 Sep", modal_price: 31 },
];

export const SEED_AI_PREDICTIONS: Record<string, AIPrediction> = {
  "Tomato": {
    crop_name: "Tomato",
    market: "Bowenpally / Hyderabad Urban",
    current_modal_price: 31,
    predicted_min_price: 34,
    predicted_max_price: 42,
    predicted_modal_price: 38,
    trend: "UPWARD",
    horizon: "Next 7 Days (Oct 1 - Oct 7)",
    confidence_percentage: 84,
    factors: [
      "Heavy unseasonal rains in Madanapalle (Andhra Pradesh supply belt) disrupting arrivals",
      "Festival demand surge expected for upcoming Navratri period",
      "Local Shamshabad/Medchal arrivals dropping by 18% week-on-week",
    ],
    disclaimer: "Estimated forecast based on historical mandi arrivals, weather alerts, and wholesale trends. Advisory only; actual spot prices subject to daily yard auctions.",
    last_updated: "2026-09-30T07:00:00Z",
  },
  "Red Chili (Dry)": {
    crop_name: "Red Chili (Dry)",
    market: "Enumamula / Warangal",
    current_modal_price: 215,
    predicted_min_price: 210,
    predicted_max_price: 228,
    predicted_modal_price: 222,
    trend: "UPWARD",
    horizon: "Next 7 Days",
    confidence_percentage: 88,
    factors: [
      "Strong export procurement demand from East Asian spice grinders",
      "Cold-storage outflow steady with low distress selling by farmers",
      "Tight supply of high-grade Teja variety in international trade",
    ],
    disclaimer: "Estimated forecast based on cold-storage data and export inquiries. Advisory only.",
    last_updated: "2026-09-30T07:00:00Z",
  },
};

export const SEED_GOVERNMENT_SCHEMES: GovernmentScheme[] = [
  {
    id: "sch1",
    name: "Rythu Bharosa / Rythu Bandhu Scheme",
    telugu_name: "రైతు భరోసా / రైతు బంధు పెట్టుబడి సహాయం",
    description: "Direct investment support scheme providing financial grant per acre per season to eliminate agricultural indebtedness and assist farmers in purchasing seeds, fertilizers, and field labor.",
    state: "Telangana",
    farmer_category: ["SMALL_MARGINAL", "ALL"],
    applicable_crops: ["All Crops", "Paddy", "Cotton", "Chili", "Pulses"],
    eligibility: [
      "Farmer must own agricultural land in Telangana recorded in Dharani Portal / RoR 1B.",
      "Must have an active bank account linked with Aadhaar.",
      "Both small, marginal, and regular landholding farmers qualify.",
    ],
    benefits: [
      "Direct DBT cash transfer directly into farmer bank account.",
      "Investment support of ₹7,500 per acre per season (Kharif & Rabi).",
      "Zero repayment obligation (100% grant, not a loan).",
    ],
    required_documents: [
      "Pattadar Passbook / Dharani Land Record Khata Number",
      "Aadhaar Card copy",
      "Bank Account Passbook (with IFSC code)",
      "Mobile number linked to Aadhaar",
    ],
    application_process: [
      "Step 1: Check your land listing on Telangana Dharani Portal (dharani.telangana.gov.in).",
      "Step 2: Submit Pattadar Passbook and bank details to your local Agriculture Extension Officer (AEO).",
      "Step 3: AEO verifies land records physically and approves the portal entry.",
      "Step 4: Grant is disbursed via RBI DBT directly into Aadhaar-seeded bank account.",
    ],
    official_url: "https://rythubandhu.telangana.gov.in",
    source: "Department of Agriculture, Government of Telangana",
    last_verified: "2026-09-01",
  },
  {
    id: "sch2",
    name: "Rythu Bima (Farmer Group Life Insurance Scheme)",
    telugu_name: "రైతు బీమా (రైతు సమగ్ర జీవిత బీమా పథకం)",
    description: "Pioneering state-sponsored life insurance ensuring immediate financial relief and livelihood security to the families of deceased farmers regardless of cause of death.",
    state: "Telangana",
    farmer_category: ["ALL"],
    applicable_crops: ["All Agricultural Landholders"],
    eligibility: [
      "Farmer age must be between 18 to 59 years.",
      "Must possess valid Pattadar passbook in Telangana.",
      "Premium is 100% paid by the Government of Telangana to LIC of India.",
    ],
    benefits: [
      "₹5,00,000 (Five Lakhs) direct payout to nominee within 10 days of claim.",
      "Covers both natural death and accidental death.",
      "Zero premium burden on the farmer family.",
    ],
    required_documents: [
      "Pattadar Passbook copy",
      "Aadhaar Card of Farmer & Nominee",
      "Nominee bank account details",
      "Death certificate (in case of claim)",
    ],
    application_process: [
      "Enrollment is conducted annually through village Agriculture Extension Officers (AEOs).",
      "Fill the simple nomination form and provide Pattadar passbook details.",
      "Policy certificate is issued under LIC group insurance.",
    ],
    official_url: "https://rythubima.telangana.gov.in",
    source: "Government of Telangana & Life Insurance Corporation of India (LIC)",
    last_verified: "2026-09-01",
  },
  {
    id: "sch3",
    name: "Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)",
    telugu_name: "ప్రధాన మంత్రి కిసాన్ సమ్మాన్ నిధి (PM-కిసాన్)",
    description: "Central sector scheme providing income support of ₹6,000 per year in three equal installments to all landholding farmer families across India.",
    state: "Central",
    farmer_category: ["SMALL_MARGINAL", "ALL"],
    applicable_crops: ["All Crops"],
    eligibility: [
      "Landholding farmer families with cultivable landholding in their names.",
      "Excludes institutional landholders and high-income taxpayers.",
      "Mandatory eKYC completion on pmkisan.gov.in.",
    ],
    benefits: [
      "₹6,000 per year transferred in 3 equal installments of ₹2,000 every 4 months.",
      "Seamless DBT to Aadhaar-enabled bank accounts.",
    ],
    required_documents: [
      "Aadhaar Card",
      "Land ownership documents / RoR 1B",
      "Active bank account details",
    ],
    application_process: [
      "Visit pmkisan.gov.in and click on 'New Farmer Registration'.",
      "Enter Aadhaar and mobile number, select Telangana and district.",
      "Enter land survey details and complete OTP e-KYC.",
    ],
    official_url: "https://pmkisan.gov.in",
    source: "Ministry of Agriculture & Farmers Welfare, Govt of India",
    last_verified: "2026-09-15",
  },
  {
    id: "sch4",
    name: "Telangana State Micro Irrigation Project (TSMIP)",
    telugu_name: "తెలంగాణ సూక్ష్మ నీటిపారుదల పథకం (డ్రిప్ & స్ప్రింక్లర్ సబ్సిడీ)",
    description: "Heavy subsidy program for modern drip and sprinkler irrigation equipment to conserve groundwater and maximize crop yield across Telangana drylands.",
    state: "Telangana",
    farmer_category: ["SMALL_MARGINAL", "ALL"],
    applicable_crops: ["Chili", "Vegetables", "Cotton", "Orchards", "Pulses"],
    eligibility: [
      "Farmers owning land with an existing water source (Borewell/Well/Farm Pond).",
      "100% subsidy for SC/ST farmers up to 5 acres.",
      "90% subsidy for BC, Small & Marginal farmers.",
      "80% subsidy for other general category farmers.",
    ],
    benefits: [
      "Saves up to 50% irrigation water and 30% electricity.",
      "Increases vegetable and orchard yield by 25-40%.",
      "Direct installation of certified drip lines and fertigation tanks on field.",
    ],
    required_documents: [
      "Pattadar Passbook",
      "Caste Certificate (for SC/ST/BC subsidy slabs)",
      "Aadhaar card",
      "Electricity service connection or water source certificate",
    ],
    application_process: [
      "Apply through MeeSeva portal or nearest Horticulture Officer.",
      "Horticulture field officer conducts site inspection and approves estimate.",
      "Pay non-subsidized farmer share via DD, and authorized agency installs drip system.",
    ],
    official_url: "https://tsmip.telangana.gov.in",
    source: "Department of Horticulture, Govt of Telangana",
    last_verified: "2026-08-20",
  },
];

export const SEED_FERTILIZER_GUIDES: FertilizerGuidance[] = [
  {
    id: "fg1",
    crop: "Paddy / Rice (వరి)",
    growth_stage: "BASAL",
    soil_condition: "Alluvial / Black Cotton soil with medium organic matter",
    recommended_fertilizers: [
      {
        name: "DAP (Di-ammonium Phosphate) or Complex 20:20:0:13",
        dosage_per_acre: "50 kg DAP + 25 kg MOP (Muriate of Potash)",
        application_method: "Incorporate into soil during last puddling before transplanting",
        timing: "Day of final puddling / pre-transplanting",
      },
      {
        name: "Zinc Sulphate (21%)",
        dosage_per_acre: "10-20 kg / acre",
        application_method: "Broadcast evenly; do not mix directly with phosphatic fertilizers",
        timing: "Basal application to prevent Khaira disease / zinc deficiency",
      },
    ],
    organic_alternatives: [
      "Well-decomposed Farm Yard Manure (FYM): 4-5 tonnes per acre",
      "Green manure crops (Daincha or Sunhemp) ploughed 10 days before puddling",
    ],
    precautions: [
      "Never top-dress DAP on standing water; always incorporate into root zone.",
      "Maintain a 4-day gap between Zinc Sulphate and Phosphorus fertilizer applications.",
    ],
    source: "Professor Jayashankar Telangana State Agricultural University (PJTSAU) Package of Practices",
    source_url: "https://pjtsau.edu.in",
    last_verified: "2026-08-15",
  },
  {
    id: "fg2",
    crop: "Chili / Mirchi (మిర్చి)",
    growth_stage: "FLOWERING",
    soil_condition: "Well-drained red loamy or medium black soil",
    recommended_fertilizers: [
      {
        name: "13:00:45 (Potassium Nitrate) & 19:19:19",
        dosage_per_acre: "3-4 kg per acre through drip fertigation or foliar spray at 5g/L",
        application_method: "Fertigation every 5 days during active blooming",
        timing: "45-65 days after transplanting (Flowering initiation)",
      },
      {
        name: "Boron (Solubor 20%)",
        dosage_per_acre: "1 to 1.5 grams per liter foliar spray",
        application_method: "Foliar mist spray in late afternoon",
        timing: "Peak flowering to avoid flower/fruit drop",
      },
    ],
    organic_alternatives: [
      "Panchagavya (3% spray in cool evening hours)",
      "Vermicompost tea enriched with Trichoderma viride",
    ],
    precautions: [
      "Avoid excess nitrogen during flowering as it triggers vegetative growth and flower shedding.",
      "Maintain steady soil moisture; water stress during flowering causes blossom end rot.",
    ],
    source: "Telangana State Horticulture University (SKLTSHU) & PJTSAU",
    source_url: "https://skltshu.ac.in",
    last_verified: "2026-08-20",
  },
  {
    id: "fg3",
    crop: "Tomato (టమాట)",
    growth_stage: "FRUITING",
    soil_condition: "Sandy loam rich in organic carbon, pH 6.0 - 7.0",
    recommended_fertilizers: [
      {
        name: "Calcium Nitrate + 0:0:50 (SOP)",
        dosage_per_acre: "5 kg Calcium Nitrate + 4 kg SOP per acre weekly",
        application_method: "Drip fertigation or ring application around root basin",
        timing: "Fruit development and color turning stage",
      },
    ],
    organic_alternatives: [
      "Bone meal and wood ash for natural potassium and calcium",
      "Fermented Jeevamrutha 200 liters/acre with flood/drip irrigation",
    ],
    precautions: [
      "Calcium deficiency causes black sunken spots at tomato base (Blossom End Rot).",
      "Do not combine Calcium Nitrate with Sulphate fertilizers in the same fertigation tank.",
    ],
    source: "ICAR - Indian Institute of Horticultural Research (IIHR)",
    source_url: "https://iihr.res.in",
    last_verified: "2026-09-01",
  },
];

export const SEED_WEATHER_DATA: WeatherData = {
  location: "Hyderabad & Rangareddy Agri Belt",
  district: "Rangareddy",
  state: "Telangana",
  temperature: 29.4,
  feels_like: 31.2,
  humidity: 68,
  rainfall_mm: 2.4,
  wind_speed_kmh: 11.8,
  weather_condition: "Partly Cloudy with Scattered Showers",
  icon_type: "PARTLY_CLOUDY",
  forecast: [
    { date: "2026-09-30", day_name: "Today", temp_max: 31, temp_min: 23, condition: "Light Showers", rain_probability: 45 },
    { date: "2026-10-01", day_name: "Thursday", temp_max: 32, temp_min: 22, condition: "Mostly Sunny", rain_probability: 15 },
    { date: "2026-10-02", day_name: "Friday", temp_max: 33, temp_min: 23, condition: "Sunny & Dry", rain_probability: 10 },
    { date: "2026-10-03", day_name: "Saturday", temp_max: 31, temp_min: 22, condition: "Scattered Rain", rain_probability: 55 },
    { date: "2026-10-04", day_name: "Sunday", temp_max: 30, temp_min: 21, condition: "Cloudy", rain_probability: 30 },
  ],
  farming_advisory: "Favorable conditions for morning vegetable harvesting. Avoid heavy foliar fertilizer sprays this evening due to scattered rain probability. Ideal weather for chili post-harvest sun drying on Friday.",
  alerts: [
    "Light evening thunderstorm alert in Rangareddy & Medchal districts",
    "Favorable moisture for Rabi sowing field preparation starting weekend",
  ],
  source: "IMD Hyderabad Meteorological Centre & Open-Meteo Agro API",
  updated_at: "2026-09-30T07:15:00Z",
};

export const SEED_LITERACY_GUIDES: DigitalLiteracyGuide[] = [
  {
    id: "lit1",
    slug: "upi-qr-safety",
    title: "Safe UPI & QR Code Payments (UPI భద్రత)",
    telugu_title: "సురక్షిత UPI చెల్లింపులు & మోసాల నివారణ",
    summary: "Learn how to receive and send payments safely using PhonePe, Google Pay, or Paytm. Crucial rule: You NEVER need to enter your UPI PIN to receive money.",
    telugu_summary: "ఫోన్‌పే, గూగుల్‌పే ద్వారా డబ్బులు స్వీకరించే సరైన పద్ధతి. ముఖ్యాంశం: మీ ఖాతాలోకి డబ్బులు రావడానికి ఎప్పుడూ UPI పిన్ (PIN) నొక్కవలసిన అవసరం లేదు.",
    category: "PAYMENTS_UPI",
    icon: "ShieldAlert",
    steps: [
      {
        step_number: 1,
        instruction: "To receive payment, show your QR Code or give your Mobile Number. The buyer scans and pays directly into your bank.",
        telugu_instruction: "డబ్బులు తీసుకోవడానికి మీ క్యూఆర్ (QR) కోడ్ చూపించండి లేదా మీ మొబైల్ నంబర్ ఇవ్వండి.",
        tip: "Keep a laminated printout of your PhonePe/GPay QR code at your farm or collection point.",
      },
      {
        step_number: 2,
        instruction: "NEVER enter your 4-digit or 6-digit secret UPI PIN when receiving money.",
        telugu_instruction: "ఎవరైనా డబ్బులు పంపుతున్నామని చెప్పి మీ రహస్య పిన్ (PIN) అడిగితే ఎట్టి పరిస్థితుల్లోనూ ఇవ్వకండి.",
        tip: "PIN is entered ONLY when you are sending money out of your account.",
        warning: "Scammers may send a 'Collect Request' claiming they are advancing crop payment. Clicking 'Approve' and entering your PIN deducts your money!",
      },
      {
        step_number: 3,
        instruction: "Verify the bank SMS or in-app payment voice alert before handing over your produce.",
        telugu_instruction: "మీ ఖాతాలో డబ్బులు జమైనట్లు మీ బ్యాంక్ నుండి వచ్చిన అధికారిక SMS లేదా యాప్ సౌండ్ బాక్స్ శబ్దం విన్న తర్వాతే సరుకు ఇవ్వండి.",
        tip: "Check your account balance directly in the app to be 100% sure.",
      },
    ],
  },
  {
    id: "lit2",
    slug: "using-agrovista",
    title: "Direct Produce Listing on AgroVista (ఆగ్రోవిస్టా వాడే విధానం)",
    telugu_title: "ఆగ్రోవిస్టాలో పంటను నేరుగా ఎలా అమ్మాలి?",
    summary: "How to take a photo of your fresh harvest, set your price higher than middleman yard rates, and fulfill orders with home pickup.",
    telugu_summary: "మీ పొలంలో పండిన పంట ఫోటో తీసి, సరసమైన ధర నిర్ణయించి, మధ్యవర్తులు లేకుండా వినియోగదారులకు ఎలా అమ్మవచ్చో తెలుసుకోండి.",
    category: "AGROVISTA",
    icon: "Sprout",
    steps: [
      {
        step_number: 1,
        instruction: "Click '+ Add Produce' on your Farmer Dashboard. Take a clear photo of your harvested vegetables or crops in daylight.",
        telugu_instruction: "రైతు డాష్‌బోర్డ్‌లో '+ Add Produce' నొక్కండి. పగటి వెలుతురులో పంట ఫోటోను స్పష్టంగా తీయండి.",
        tip: "Good clean photos attract premium city buyers quickly.",
      },
      {
        step_number: 2,
        instruction: "Check the Live Mandi Reference Price displayed on the screen. Set your Farmer Price to earn 20-40% more than yard commission agents.",
        telugu_instruction: "స్క్రీన్‌పై కనిపించే మార్కెట్ యార్డ్ ధరను చూడండి. దళారీలకు ఇచ్చే ధర కంటే మీకు 20-30% ఎక్కువ లాభం వచ్చేలా ధర నమోదు చేయండి.",
        tip: "AgroVista customers love paying farmers directly while saving money compared to supermarkets.",
      },
      {
        step_number: 3,
        instruction: "When a customer orders, tap 'Confirm' and pack the produce. Our local AgroVista delivery partner collects it from your village.",
        telugu_instruction: "కస్టమర్ ఆర్డర్ చేయగానే 'Confirm' నొక్కి ప్యాక్ చేయండి. మన డెలివరీ ఏజెంట్ మీ గ్రామానికి వచ్చి సరుకు తీసుకుంటారు.",
        tip: "Keep the weight accurate to build customer trust and repeat orders.",
      },
    ],
  },
  {
    id: "lit3",
    slug: "dharani-schemes-check",
    title: "Checking Government DBT & Schemes Online",
    telugu_title: "ప్రభుత్వ రైతు బంధు & పిఎం-కిసాన్ స్థితి ఆన్‌లైన్‌లో చూడటం",
    summary: "Step-by-step guide to check whether your Rythu Bandhu or PM-KISAN installment has credited to your bank account without standing in bank queues.",
    telugu_summary: "బ్యాంకు వద్ద క్యూలో నిలబడకుండా మీ మొబైల్ లేదా మీసేవ ద్వారా రైతు బంధు జమైందో లేదో తెలుసుకునే మార్గం.",
    category: "GOV_SERVICES",
    icon: "Landmark",
    steps: [
      {
        step_number: 1,
        instruction: "Visit pmkisan.gov.in and click on 'Know Your Status'. Enter your Registration Number or Mobile number.",
        telugu_instruction: "pmkisan.gov.in వెబ్‌సైట్‌లో 'Know Your Status' పై నొక్కి మీ మొబైల్ లేదా రిజిస్ట్రేషన్ నంబర్ నమోదు చేయండి.",
        tip: "Ensure your Aadhaar is linked to your bank account (Aadhaar NPCI mapping).",
      },
      {
        step_number: 2,
        instruction: "For Telangana Rythu Bandhu, visit the official portal and select your Mandal, Village, and Pattadar passbook number.",
        telugu_instruction: "తెలంగాణ రైతు బంధు పోర్టల్‌లో మీ మండలం, గ్రామం మరియు పట్టాదారు పాస్‌బుక్ నంబర్ ఎంచుకోండి.",
        tip: "If credit is delayed, meet your village Agriculture Extension Officer (AEO) to verify bank IFSC updates.",
      },
    ],
  },
];
